@HostAddress = http://localhost:5200

### Register
POST {{HostAddress}}/register
Content-Type: application/json

{
  "email": "test@abc.com",
  "password": "abcdef"
}

### Login
POST {{HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "test@abc.com",
  "password": "abcdef"
}

> {% client.global.set("auth_token", response.body.token); %}

### Logged in
GET {{HostAddress}}/me
Authorization: Bearer {{auth_token}}

### Create group
POST {{HostAddress}}/group
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Croatia Trip ⛱️"
}

> {% client.global.set("group_id", response.body.id); %}

### List groups
GET {{HostAddress}}/group
Authorization: Bearer {{auth_token}}
Accept: application/json

### Get group
GET {{HostAddress}}/group/{{group_id}}
Authorization: Bearer {{auth_token}}
Accept: application/json

### Delete group
DELETE {{HostAddress}}/group/{{group_id}}
Authorization: Bearer {{auth_token}}

### Add member
POST {{HostAddress}}/group/{{group_id}}/members
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "userEmail": "HEJ@abc.com"
}

### Remove member
DELETE {{HostAddress}}/group/{{group_id}}/members
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "userEmail": "HEJ@abc.com"
}

### Create expense
POST {{HostAddress}}/group/{{group_id}}/expenses
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "title": "Lunch sandwich",
  "amount": 50
}

### Create expense with invalid splits
POST {{HostAddress}}/group/{{group_id}}/expenses
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "title": "Lunch ??? very expensive",
  "amount": 50,
  "shares": {
    "0196b5d2-ea99-72f1-b7dd-80337c9ccbdd": 4
  }
}

### List expenses
GET {{HostAddress}}/group/{{group_id}}/expenses
Authorization: Bearer {{auth_token}}
Accept: application/json

### Delete expense
@expense_id = 0196b633-d771-7838-bf40-44997b58bf01
DELETE {{HostAddress}}/group/{{group_id}}/expenses/{{expense_id}}
Authorization: Bearer {{auth_token}}