@HostAddress = http://localhost:5200

### Register
POST {{HostAddress}}/register
Content-Type: application/json

{
  "email": "test@abc.com",
  "password": "abcdef"
}

### Login
POST {{HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "test@abc.com",
  "password": "abcdef"
}

> {% client.global.set("auth_token", response.body.token); %}

### Logged in
GET {{HostAddress}}/me
Authorization: Bearer {{auth_token}}

### Create expense
POST {{HostAddress}}/expenses
Authorization: Bearer {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "title": "Lunch sandwich",
  "amount": 50,
  "splits": {
    "abc": 51
  }
}

### List expenses
GET {{HostAddress}}/expenses
Authorization: Bearer {{auth_token}}
Accept: application/json